name: SignEdit
version: 1.0-RELEASE
main: de.blaumeise03.signEdit.SignEdit
description: A sign editor
api-version: 1.15
author: Blaumeise03
website: http://blaumeise03.de/

permissions:
  signEdit.edit:
    default: true
    description: Edit Signs
  signEdit.*:
    default: op
    description: Wildcard
    children:
      signEdit.edit: true